import { useState } from 'react';
import { CalendarDays, ChevronDown, FileScan, Search, Trash2, X } from 'lucide-react';
import { Link } from '@/lib/link';
import { useQueryClient } from '@tanstack/react-query';
import { ContentType, getGetScanSummaryQueryKey, getListScansQueryKey, RiskLevel, useDeleteScan, useListScans } from '@workspace/api-client-react';
import { EmptyState, ErrorState, RiskBadge, SectionEyebrow, SkeletonBlock } from '@/components/qr-ui';
import { useToast } from '@/hooks/use-toast';

function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value)); }

export default function HistoryPage() {
  const queryClient = useQueryClient();
  const { toast } = useToast();
  const [risk, setRisk] = useState<RiskLevel | undefined>();
  const [content, setContent] = useState<ContentType | undefined>();
  const [search, setSearch] = useState('');
  const [confirmId, setConfirmId] = useState<string | null>(null);
  const params = { page: 1, pageSize: 50, riskLevel: risk, contentType: content, search: search || undefined };
  const query = useListScans(params);
  const deletion = useDeleteScan();
  const items = query.data?.items ?? [];
  function deleteScan() {
    if (!confirmId) return;
    deletion.mutate({ id: confirmId }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListScansQueryKey() }); queryClient.invalidateQueries({ queryKey: getGetScanSummaryQueryKey() }); setConfirmId(null); toast({ title: 'Observation removed', description: 'The report was deleted from this session.' }); }, onError: () => toast({ title: 'Could not remove observation', description: 'Please try again.' }) });
  }
  return <div className="page-enter space-y-8"><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><SectionEyebrow>Archive / 03</SectionEyebrow><h1 className="mt-3 font-display text-[clamp(2.8rem,6vw,5rem)] leading-[.9] tracking-[-.05em]">A record of<br /><i>what you saw.</i></h1><p className="mt-5 max-w-lg text-[14px] leading-7 text-muted-foreground">Scans are kept for this browser session only. Search the evidence, revisit a report, or clear it away.</p></div><div className="flex items-center gap-2 font-mono-ui text-[10px] uppercase tracking-[.14em] text-muted-foreground"><CalendarDays size={15} />{query.data?.total ?? 0} observations</div></header>
    <section className="rounded-2xl border border-border bg-card p-3 shadow-[var(--shadow-xs)] sm:p-4"><div className="flex flex-col gap-3 lg:flex-row"><label className="flex flex-1 items-center gap-2 rounded-xl bg-[hsl(var(--muted)/.64)] px-3"><Search size={16} className="text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search decoded preview" className="h-11 w-full bg-transparent text-[13px] outline-none placeholder:text-muted-foreground" data-testid="input-history-search" />{search && <button type="button" onClick={() => setSearch('')} className="text-muted-foreground" aria-label="Clear search" data-testid="button-clear-search"><X size={15} /></button>}</label><div className="flex gap-2"><label className="relative flex-1"><span className="sr-only">Filter by risk</span><select value={risk ?? ''} onChange={(event) => setRisk((event.target.value || undefined) as RiskLevel | undefined)} className="h-11 w-full appearance-none rounded-xl border border-border bg-card px-3 pr-9 text-[12px] font-medium outline-none focus:ring-2 focus:ring-ring sm:w-36" data-testid="select-risk-filter"><option value="">All risk levels</option>{Object.values(RiskLevel).map((value) => <option value={value} key={value}>{value[0].toUpperCase() + value.slice(1)}</option>)}</select><ChevronDown size={15} className="pointer-events-none absolute right-3 top-3.5 text-muted-foreground" /></label><label className="relative flex-1"><span className="sr-only">Filter by content</span><select value={content ?? ''} onChange={(event) => setContent((event.target.value || undefined) as ContentType | undefined)} className="h-11 w-full appearance-none rounded-xl border border-border bg-card px-3 pr-9 text-[12px] font-medium outline-none focus:ring-2 focus:ring-ring sm:w-36" data-testid="select-content-filter"><option value="">All content</option>{Object.values(ContentType).map((value) => <option value={value} key={value}>{value.replace('_', ' ')}</option>)}</select><ChevronDown size={15} className="pointer-events-none absolute right-3 top-3.5 text-muted-foreground" /></label></div></div></section>
    {query.isLoading ? <div className="space-y-2">{[1, 2, 3, 4].map((n) => <SkeletonBlock key={n} className="h-[78px]" />)}</div> : query.isError ? <ErrorState onRetry={() => query.refetch()} detail="History could not be read right now." /> : items.length === 0 ? <EmptyState title={search || risk || content ? 'No matching observations' : 'Nothing archived yet'} detail={search || risk || content ? 'Try widening the filters. Your session history is still intact.' : 'Once you analyze a QR image, its report will live here for quick reference.'} action={!(search || risk || content) ? <Link href="/scan" className="rounded-xl bg-primary px-4 py-2.5 text-[12px] font-semibold text-primary-foreground" data-testid="button-history-scan">Start a scan</Link> : undefined} /> : <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-[var(--shadow-xs)]"><div className="hidden grid-cols-[1fr_140px_120px_48px] gap-4 border-b border-border bg-[hsl(var(--muted)/.45)] px-5 py-3 font-mono-ui text-[9px] uppercase tracking-[.15em] text-muted-foreground sm:grid"><span>Decoded preview</span><span>Observed</span><span>Assessment</span><span /></div>{items.map((item) => <div key={item.id} className="group grid items-center gap-3 border-b border-border px-4 py-4 last:border-0 sm:grid-cols-[1fr_140px_120px_48px] sm:gap-4 sm:px-5"><Link href={`/result/${item.id}`} className="flex min-w-0 items-center gap-3" data-testid={`link-history-${item.id}`}><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[hsl(var(--muted))] text-muted-foreground"><FileScan size={16} /></span><span className="min-w-0"><span className="block truncate text-[13px] font-semibold group-hover:text-[hsl(var(--primary))]">{item.preview || 'Untitled QR destination'}</span><span className="mt-1 block font-mono-ui text-[9px] uppercase tracking-[.08em] text-muted-foreground">{item.contentType.replace('_', ' ')}</span></span></Link><span className="hidden text-[11px] text-muted-foreground sm:block">{formatDate(item.createdAt)}</span><span><RiskBadge level={item.riskLevel} score={item.riskScore} /></span><button type="button" onClick={() => setConfirmId(item.id)} className="justify-self-end rounded-lg p-2 text-muted-foreground opacity-70 hover:bg-[hsl(var(--destructive)/.1)] hover:text-[hsl(var(--destructive))] sm:opacity-0 sm:group-hover:opacity-100" aria-label={`Delete ${item.preview || 'observation'}`} data-testid={`button-delete-${item.id}`}><Trash2 size={15} /></button></div>)}</div>}
    {confirmId && <div className="fixed inset-0 z-50 grid place-items-center bg-[hsl(var(--foreground)/.3)] p-5" role="dialog" aria-modal="true" data-testid="dialog-delete-confirm"><div className="w-full max-w-sm rounded-2xl border border-border bg-card p-6 shadow-[var(--shadow-xl)]"><div className="mb-4 flex items-start justify-between"><div className="grid size-10 place-items-center rounded-xl bg-[hsl(var(--destructive)/.1)] text-[hsl(var(--destructive))]"><Trash2 size={18} /></div><button type="button" onClick={() => setConfirmId(null)} className="rounded-lg p-2 text-muted-foreground hover:bg-muted" aria-label="Close delete dialog" data-testid="button-close-delete-dialog"><X size={17} /></button></div><h2 className="font-display text-2xl">Remove this report?</h2><p className="mt-2 text-[13px] leading-relaxed text-muted-foreground">This observation will be removed from the current browser session. The decoded destination will not be revisited.</p><div className="mt-6 flex gap-2"><button type="button" onClick={() => setConfirmId(null)} className="flex-1 rounded-xl border border-border px-4 py-2.5 text-[12px] font-semibold hover-elevate" data-testid="button-cancel-delete">Keep report</button><button type="button" onClick={deleteScan} disabled={deletion.isPending} className="flex-1 rounded-xl bg-destructive px-4 py-2.5 text-[12px] font-semibold text-destructive-foreground disabled:opacity-50" data-testid="button-confirm-delete">{deletion.isPending ? 'Removing…' : 'Remove report'}</button></div></div></div>}
  </div>;
}